language: go

go:
    - 1.13
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - COVERALLS="-repotoken $COVERALLS_TOKEN" ./scripts/testcoverage.sh

env:
    - secure: "DygCBexI9tfMqcZoAQsuhhgCtCNRqkEWtigZoal1gVTvDHCFSBbgs3DfwkVgIXITV8Al8KejOWOFRTo2EmTluRuRSiQIFI0DL1cdU/PyxmZxLVK0tF3X8Yh7yTEMxpcl3jJf+8AVIHzUsspASWcV1qyp70JP0Kgjo81qkbIHPzg="
